Tags
astronomer/terraform-aws-astronomer-aws pull request #7
Opened 2019-06-25 17:03 UTC by ianstanton

* Allows users to define AWS Tags in their `*.tfvars` file.
* Users define tags as follows:
```
tags = { "key-1" = "value-1",
         "key-2" = "value-2",
         "key-n" = "value-n" 
}
```
* `Deployment ID` tag will be defined by default
* Format changes were made after running `terraform fmt`
* Related to #4

2019-06-27 16:35 UTC, kaxil approved these changes

2019-06-27 16:36 UTC, kaxil commented
I have approved as it looks good but there are Merge conflicts that you will have to resolve @ianstanton

2019-06-28 12:50 UTC, sjmiller609 requested changes
It's looking good, and thanks for the formatting. There are a few resources that could also use tags:

- resource "aws_lambda_function" "elb_lookup"
- resource "aws_iam_role" "elb_lookup_role"
- resource "aws_security_group" "all_worker_mgmt"
- Module “vpc”
- resource "aws_key_pair" "bastion_ssh_key"
- resource "aws_db_parameter_group" "aurora_db_postgres_parameter_group"
- resource "aws_rds_cluster_parameter_group" "aurora_cluster_postgres_parameter_group" 

2019-06-28 12:50 UTC, sjmiller609 commented on bastion.tf
> +  tags   = local.tags
I think we don't need this line

2019-06-28 12:50 UTC, sjmiller609 commented on db.tf
>  resource "aws_db_parameter_group" "aurora_db_postgres_parameter_group" {
tags on this resource and the one below (noted in list below)

2019-06-28 12:50 UTC, sjmiller609 commented on domain.tf
> +  rsa_bits  = "4096"
I think this is the bit with the merge conflict. we were having issues specifying the key length, so when you resolve the conflicts, please omit the key length in the resource and the rest in this file.

2019-07-01 16:30 UTC, ianstanton commented
> It's looking good, and thanks for the formatting. There are a few resources that could also use tags:
> 
> * resource "aws_lambda_function" "elb_lookup"
> * resource "aws_iam_role" "elb_lookup_role"
> * resource "aws_security_group" "all_worker_mgmt"
> * Module “vpc”
> * resource "aws_key_pair" "bastion_ssh_key"
> * resource "aws_db_parameter_group" "aurora_db_postgres_parameter_group"
> * resource "aws_rds_cluster_parameter_group" "aurora_cluster_postgres_parameter_group"

Added to these resources. Going to do a quick test.

2019-07-01 16:39 UTC, ianstanton commented
> > It's looking good, and thanks for the formatting. There are a few resources that could also use tags:
> > 
> > * resource "aws_lambda_function" "elb_lookup"
> > * resource "aws_iam_role" "elb_lookup_role"
> > * resource "aws_security_group" "all_worker_mgmt"
> > * Module “vpc”
> > * resource "aws_key_pair" "bastion_ssh_key"
> > * resource "aws_db_parameter_group" "aurora_db_postgres_parameter_group"
> > * resource "aws_rds_cluster_parameter_group" "aurora_cluster_postgres_parameter_group"
> 
> @sjmiller609 Added to these resources. Going to do a quick test.

Edit: Removed tag from resource "aws_key_pair" "bastion_ssh_key". Key pair does not support tags.

2019-07-02 13:40 UTC, sjmiller609 approved these changes
perfect!

2019-07-02 13:41 UTC, merged

2019-07-02 13:42 UTC, sjmiller609 commented
https://github.com/astronomer/terraform-aws-astronomer-aws/releases/tag/1.0.9